### ISSUE TITLE
Feature Request: Training Code

### ISSUE THREAD

**Issue by yosh503037** [chihfanhsu/gaze_correction#1]
Thanks for providing the code for the paper -- this is extremely neat! I was wondering if you had the code you used to train the model on hand, since I was looking to retrain the model and couldn't figure out exactly how to go about doing that.

**Comment by chihfanhsu** [comment]
I've uploaded an example for training the model and a small size training dataset.
You can try these codes.
I am preparing the code for generating the training inputs from the raw gaze dataset.
I hope I can upload these days.

**Comment by yosh503037** [comment]
Awesome, thanks for the extremely fast update! I'll check it out and will update the thread if I encounter any issues but will close the issue in the meantime.

**Comment by yosh503037** [comment]
Edit: Actually, I'm going to keep the issue open just until the code to transform the raw dataset to the training/validation dataset is available so that we can keep track of this "training feature request" as a single issue. But I can confirm that the training code worked practically without a hitch!

**Comment by yosh503037** [comment]
Hey @chihfanhsu, just wanted to bump this to see if there was any progress on the code to generate the training inputs from the raw gaze dataset. Wanted to try training on some samples I was capturing!

**Comment by chihfanhsu** [comment]
Already uploaded!
The code is put in the training/ folder.
