### ISSUE TITLE
Question about the provided DIRL dataset

### ISSUE THREAD

**Issue by etudemin** [chihfanhsu/gaze_correction#16]
Hi chihfanhsu,

The work is great and thanks for sharing!

I am trying to retrain the model with the provided DIRL dataset. However, when I use generate_training_inputs_from_raw_dataset.py to crop the eye patches, some of the eye patches (especially low pitch cases) suffer from black boundaries. The visualized example is shown below (0000_0P_-10H_-20V.png): 
![0000_0P_-10H_-20V_L](https://user-images.githubusercontent.com/10068773/145239234-09b36d99-5b8c-4c4b-9842-2e002c9ac21b.png)

Seems that the issue comes from limited visible eye regions in the provided DIRL dataset. Excuse me, would there be a dataset update in the near future or any suggestions?

Thank you very much.

**Comment by chihfanhsu** [comment]
I do not have the raw images anymore. I think you can just fill the filtered region with the nearest skin color.

**Comment by etudemin** [comment]
Hi chihfanhsu,

Thanks for your kind reply.
