### ISSUE TITLE
No download permission

### ISSUE THREAD

**Issue by YJYlala** [chihfanhsu/gaze_correction#17]
i want to down DIRL dataset to study , it include images and labels，but have no down permission for images
can u help me

**Comment by chihfanhsu** [comment]
I think it is ok now

**Comment by YJYlala** [comment]
Dear  chifansu:

i want to know how this dataset work？
 it include image and labels, that means the eye image (I) and the Anchor map(MA). and what about the rotation angle?  it is automatic calculate when the video frame come?
 if we need to train the network , what is the target image?
why we need to transforms the eyeball rotation angles αw2c from a two-dimensional (2D) vector to a 16-dimensional vector (16D) and duplicates the 16D vector to form a feature map?
Please


Thank you for your answer and patient!!
Regards
Jingyou Yang










At 2022-03-19 19:53:11, "Chih-Fan Hsu" ***@***.***> wrote:

I think it is ok now

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
