### ISSUE TITLE
some Question about the dataset and network

### ISSUE THREAD

**Issue by YJYlala** [chihfanhsu/gaze_correction#19]
i want to know how this dataset work？
 it include image and labels, that means the eye image (I) and the Anchor map(MA). and what about the rotation angle?  it is automatic calculate when the video frame come?
 if we need to train the network , what is the target image?
why we need to transforms the eyeball rotation angles αw2c from a two-dimensional (2D) vector to a 16-dimensional vector (16D) and duplicates the 16D vector to form a feature map?

**Comment by chihfanhsu** [comment]
The model takes two inputs, (1) an original eye image and (2) the desired rotation angle along with the x- and y-axis starting from the original eye image to generate a synthetic eye image compared to the ground truth eye image.
The main idea of expanding the rotation angles from a 2D vector to a 16-channels map is to increase the impact of the rotation angles on the model. You can redesign any kind of model structure for your demands.

You can carefully read the paper first, I remember that I have addressed these questions in the paper.

**Comment by chihfanhsu** [comment]
> The model takes two inputs, (1) an original eye image and (2) the desired rotation angle along with the x- and y-axis starting from the original eye image to generate a synthetic eye image compared to the ground truth eye image. The main idea of expanding the rotation angles from a 2D vector to a 16-channels map is to increase the impact of the rotation angles on the model. You can redesign any kind of model structure for your demands.
> 
> You can carefully read the paper first, I remember that I have addressed these questions in the paper.

By the way, please do not use GitHub issues to ask non-technical issues.
