### ISSUE TITLE
Hello! Thanks for providing such a good project.

### ISSUE THREAD

**Issue by ztrong-forever** [chihfanhsu/gaze_correction#20]
What does the sum of absolute values of partial derivatives written in your paper mean?
![image](https://user-images.githubusercontent.com/62659186/160831157-c329b41a-aee0-4ab8-b5b7-9c8ac0acc147.png)

**Comment by ztrong-forever** [comment]
![image](https://user-images.githubusercontent.com/62659186/160831920-3f74504b-64ff-43ae-afc4-8ae1cc318f2a.png)

**Comment by sunnylulu** [comment]
I am not the author, but I think the answer should be already in the paper. Please see the notes for figure 8. 

> We warp each eye image I to as similar as It to redirect the gaze. To retain the eyeball structure,
> pixels on pupil and iris should move similarly. We also expect pixels on eyelids to move similarly because of
> the low degree of freedom of eyelids.

That means the F should be same within iris.

**Comment by chihfanhsu** [comment]
Basically, it is the difference between two adjacency pixels along with the x- and y-axes. You can also calculate it by the 1D convolution with kernel [1 0 -1] such as https://en.wikipedia.org/wiki/Image_gradient?msclkid=89fdc03cbff011ec995750a27b5e2fef

Actually, you can find these in the code.
