### ISSUE TITLE
can't download the dataset

### ISSUE THREAD

**Issue by sosoIrving** [chihfanhsu/gaze_correction#24]
There is not dataset in https://sites.google.com/site/chihfanhsuwebsite/dataset. I find the 'Download the DIRL Gaze dataset!',but has not link.

**Comment by chihfanhsu** [comment]
The links work after testing. You can download them by the number after Poses.

**Comment by sosoIrving** [comment]
Thank you sincerely.



---Original---
From: "Chih-Fan ***@***.***&gt;
Date: Wed, Apr 26, 2023 10:03 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [chihfanhsu/gaze_correction] can't download the dataset (Issue#24)




 
The links work after testing. You can download them by the number after Poses.
