### ISSUE TITLE
How do I run it on M1 Max GPU or CoreML, Apple Silicon?

### ISSUE THREAD

**Issue by JeromeNelsonC** [chihfanhsu/gaze_correction#28]
I see there are no insturctions for Mac M1/M2, is it possible to make it compatible for these sytems?

**Comment by chihfanhsu** [comment]
I have no experience running TensorFlow on M1/M2 machines because I don't have these machines :Q You can check this website for more information.
https://developer.apple.com/metal/tensorflow-plugin/
