### ISSUE TITLE
mac os issues

### ISSUE THREAD

**Issue by Cabdil1** [chihfanhsu/gaze_correction#30]
hello 
i tried to use gaze correction but in my macOS it didn’t work, this app works win32 but in macos is not available win32

please do you have any solution

**Comment by thisisvk45** [comment]
@Cabdil1 For gaze correction on macOS, use Python with OpenCV and Dlib. Install dependencies (`opencv-python`, `dlib`, `imutils`) and download the Dlib facial landmarks model. Detect facial landmarks and adjust the eye regions to correct the gaze. Ensure the necessary models and scripts are compatible with macOS.

**Comment by chihfanhsu** [comment]
Thanks for the instructions.

**Comment by WangWilly** [comment]
@Cabdil1 This is my version of build [WangWilly/gaze-correction-cam](https://github.com/WangWilly/gaze-correction-cam) on the macOS (m1 chip). Take a look and welcome to leave feedback.
