### ISSUE TITLE
Can I ask you the intrinsic parameters of camera in the DIRL Gaze Dataset ?

### ISSUE THREAD

**Issue by jasminekao** [chihfanhsu/gaze_correction#4]
Hi,
    I want to use the DIRL Gaze Dataset to do some experiment, but I can't find the camera parameter. Can you share it, please? Thanks.

**Comment by chihfanhsu** [comment]
Hello, what kind of camera parameters you want to know?
For your information, we didn't perform the camera calibration to obtain the exact intrinsic and extrinsic camera parameters

**Comment by jasminekao** [comment]
I saw the paper, and there is a formula for calculating the focal length. There is a sentence:"we ask the participant to place their head d cm away from the camera". I can't find the detailed number of d.
Did i miss something?

**Comment by chihfanhsu** [comment]
Hello, you might ask the process to get the focal length f.
We use the code, https://github.com/chihfanhsu/gaze_correction/blob/master/gaze_correction_system/focal_length_calibration.ipynb, to obtain f and d also is listed in the code.

Besides, the actual estimated focal length is listed in the code, https://github.com/chihfanhsu/gaze_correction/blob/master/gaze_correction_system/config.py, and the estimated f is 650.

You might need to change f to fit your computer.

**Comment by jasminekao** [comment]
Thanks a lot!
