### ISSUE TITLE
How to use this in Android ?

### ISSUE THREAD

**Issue by shubham2652** [chihfanhsu/gaze_correction#6]
Thanks @chihfanhsu for creating this gaze correction network. I want to integrate this network with android can I ? and if yes how can i integrate this with android ?

**Comment by chihfanhsu** [comment]
Yes, I think this project can. But I am not familiar with the mobile coding. Maybe you should run the Tensorflow on the android and import the weight to the pre-build network. Implementing the system on mobile devices should be great for live broadcasting!
