### ISSUE TITLE
The gaze code has no effect and the key point results is problematic. Could you please find that whether there is any wrong in the code?

### ISSUE THREAD

**Issue by pjl1995** [chihfanhsu/gaze_correction#8]
![2](https://user-images.githubusercontent.com/16452773/89488275-20b81a00-d7da-11ea-967a-b8c767e361c1.png)

**Comment by chihfanhsu** [comment]
The facial landmark detection, Dlib, should detect the landmark from a whole face image rather than a partial one.
You can replace the landmark detection algorithm to satisfy your needs.
