### ISSUE TITLE
Eyes not centered and deformed

### ISSUE THREAD

**Issue by dbonattoj** [chihfanhsu/gaze_correction#9]
I'm trying out your code, I have small problems with my eyes:

![image](https://user-images.githubusercontent.com/28501597/94798537-08333d00-03e2-11eb-941e-2378af30d89c.png)
Left: original looking directly at the camera
Right: Generated view (I still have issues to have the eyes to look at the center of the image)

Can I do something to improve this ?

also, it is difficult to set the position of the eyes with the camera, it would be nice if we could freeze a picture where we are looking straight to the camera, and after straight to the center of the screen and the software estimate the distance.

Bests,

**Comment by chihfanhsu** [comment]
I am not pretty sure the question "I still have issues to have the eyes to look at the center of the image" means?
You need to see the face displayed on the screen, then the gaze is corrected.
Before the correction, you need to measure some coordinates, such as **the location of the camera from the center of the screen**, **the size of the screen**, **the focal length of your camera**. You can manually set these parameters in the "config" file.

For the question "can you improve this?", do you mean to improve the distortion in the images?
If the redirection angle becomes larger, the distortion inevitably becomes more serious.
Adding some loss terms to constraint the generated point flows might be a solution.
However, I think directly smooth the generated flows might also a solution.

For the third question, I was wondering why do you need to set the position of the eyes with the camera? The system will detect your eyes in the image and estimate the physical position of the eyes. To achieve this, a few parameters should be manually set (as I mentioned above). Carefully, the camera direction should be perpendicular to the extended surface of the screen.

**Comment by dbonattoj** [comment]
3) Ok! From the drawing I thought I needed to set P_c_x, P_c_y, P_c_z relatively to the center of my head/eyes, and not relatively to the center of the screen, it is now way better and make much more sense!

I still have distortions in the eyes, but is will be close enough for my purposes :)
![image](https://user-images.githubusercontent.com/28501597/94932610-9a624080-04c9-11eb-8ffe-61aba93f4170.png)

From further away (~60cm) :
![image](https://user-images.githubusercontent.com/28501597/94932876-ef05bb80-04c9-11eb-9bad-1e3c20304a23.png)

The image are better (the images are magnified around my eyes)

I'll do more experiments,

thanks!
